name: Test Coverage And Summary Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: tests/TestCoverage.Test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Required Tools
        run: |
          dotnet new tool-manifest --force
          dotnet tool install DotnetCtrfJsonReporter --local
        shell: powershell

      - name: Restore Dependencies and Build
        run: |
          dotnet restore
          dotnet build --configuration Release

      - name: Run Tests with Coverage
        run: |
          dotnet test --configuration Release --no-build --verbosity=minimal `
          --logger "trx;logfilename=output.trx;verbosity=detailed"`
          -p:CollectCoverage=true `
          -p:CoverletOutputFormat="opencover" `
          -p:CoverletOutput=TestResults/output.xml

      - name: Converting Generated TRF To JSON Report For Presentation
        if: success()
        run: dotnet tool run DotnetCtrfJsonReporter -p "TestResults/output.trx" -f "output.json" -d "TestResults" -t "mstest"
  
      - name: Test Summary Results
        uses: ctrf-io/github-test-reporter@v1
        if: success()
        with:
          report-path: 'tests/TestCoverage.Test/TestResults/output.json'
          summary-report: true
          test-report: true
          annotate: true
          failed-report: true
          skipped-report: true
          upload-artifact: true

      - name: Create Test Coverage Badge
        uses: simon-k/dotnet-code-coverage-badge@v1.0.0
        id: create_coverage_badge
        with:
          label: Unit Test Coverage
          color: brightgreen
          path: 'tests/TestCoverage.Test/TestResults/output.xml'
          gist-filename: coverage-badge.txt
          gist-id: f59d0140e2c811c0b651d6e02b84796e
          gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}  